# Generated by Django 5.0.3 on 2024-03-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                ("court_id", models.AutoField(primary_key=True, serialize=False)),
                ("court_location", models.CharField(max_length=200)),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("magistrates court", "Magistrates Court"),
                            ("supreme court", "Supreme Court"),
                            ("high court", "High Court"),
                            ("court of appeal", "Court of Appeal"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crime",
            fields=[
                (
                    "crime_type",
                    models.CharField(
                        choices=[
                            ("theft", "Theft"),
                            ("accident", "Accident"),
                            ("assault", "Assault"),
                        ],
                        max_length=100,
                    ),
                ),
                ("crime_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("penalty", models.CharField(max_length=100)),
                ("exhibit", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                ("officer_id", models.AutoField(primary_key=True, serialize=False)),
                ("officer_name", models.CharField(max_length=100)),
                ("badge_number", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")], max_length=20
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("inspector", "Inspector"),
                            ("corporal", "Corporal"),
                            ("ocs", "OCS"),
                            ("ocpd", "OCPD"),
                            ("base commander", "Base Commander"),
                            ("constable", "Constable"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliceStation",
            fields=[
                ("station_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                ("contact_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Suspect",
            fields=[
                ("suspect_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("suspect_id_number", models.IntegerField()),
                ("date_of_birth", models.DateField()),
                ("belongings", models.TextField()),
                ("date_booked", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                ("judge_id", models.AutoField(primary_key=True, serialize=False)),
                ("judge_name", models.CharField(max_length=100)),
                (
                    "judge_level",
                    models.CharField(
                        choices=[("magistrate", "Magistrate"), ("judge", "Judge")],
                        max_length=100,
                    ),
                ),
                (
                    "court_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obook_app.court",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                ("lawyer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("date_of_birth", models.DateField()),
                (
                    "court_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obook_app.court",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                ("penalty_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "crime_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalties",
                        to="obook_app.crime",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Armory",
            fields=[
                ("armor_id", models.AutoField(primary_key=True, serialize=False)),
                ("armor_name", models.CharField(max_length=100)),
                ("armor_type", models.CharField(max_length=100)),
                (
                    "officer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obook_app.policeofficer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FingerPrint",
            fields=[
                ("fingerprint_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suspect_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obook_app.suspect",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bail",
            fields=[
                ("bail_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "suspect_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obook_app.suspect",
                    ),
                ),
            ],
        ),
    ]
