# Generated by Django 5.0.3 on 2024-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_type',
            field=models.CharField(choices=[('magistrates court', 'Magistrates Court'), ('supreme court', 'Supreme Court'), ('high court', 'High Court'), ('law court', 'Law Court'), ('court of appeal', 'Court of Appeal')], max_length=20),
        ),
    ]
