# Generated by Django 5.0.3 on 2024-03-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obook_app', '0002_alter_court_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='suspect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_names', to='obook_app.suspect'),
        ),
    ]
